name: mapgoal
description: ""
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  google_fonts: ^6.2.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  flutter_map: ^6.1.0
  flutter_map_math: ^0.1.7
  latlong2: ^0.9.1
  percent_indicator: ^4.2.3
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.14.1"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  
flutter_launcher_icons:
  android: "launcher_icon"
  image_path_android:  "assets/images/gradientGPS-android.PNG"
  adaptive_icon_background: "#FFFFFF"  # Set background color (or use an image)
  adaptive_icon_foreground: "assets/images/gradientGPS-android.PNG"


  

