name: "Build APK"

on:
    push:
      branches:
        - main
        
jobs: 
  build:    
    name: Build APK  
    runs-on: self-hosted

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Set Up Flutter
          uses: subosito/flutter-action@v2
          with:
           flutter-version: '3.22.2'
           channel: 'stable'
        - name: Install Dependencies
          run: flutter pub get
        - name: Build APK
          run: flutter build apk --release