on:
  push:
    tags:
    - "v*"

name: Create Release

permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: self-hosted
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'
      - name: Install Dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --release
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: latest-apk
          path: build/app/outputs/flutter-apk/app-release.apk
  release:
    name: Create Release
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        needs: latest-apk
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - name: Upload Release APK
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.latest-apk }}
          asset_path: apk/app-release.apk
          asset_name: latest.apk